// src/styles/styles.js
import { StyleSheet } from "react-native";

// ------------------------------------------------------------
// Arquivo de estilos globais do aplicativo
// ------------------------------------------------------------
export default StyleSheet.create({
  // ---------------- Layout base ----------------
  container: {
    flex: 1,
    backgroundColor: "#f5f5f52a", // cinza claro
  },

  center: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 50,
    padding: 20,
  },
  row: { flexDirection: "row", marginTop: 10 },
  rowSpace: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  rowItem: {
    borderBottomWidth: 1,
    borderColor: "#f3f3f3",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },

  // ---------------- Textos ----------------
  h1: { fontSize: 20, fontWeight: "800", marginTop: 20 },
  h2: { fontSize: 18, fontWeight: "700" },
  h3: {
    fontSize: 16,
    fontWeight: "800",
    marginTop: 5,
    color: "#fff",
    marginLeft: 20,
  },
  h4: {
    fontSize: 40,
    fontWeight: "800",
    marginTop: 150,
    alignItems: "center",
    justifyContent: "center",
  },
  h5: {
    fontSize: 16,
    fontWeight: "800",
    marginTop: 5,
    color: "#000",
    marginLeft: 20,
  },
  p: { color: "#666", marginTop: 8, lineHeight: 20 },
  logoTitle: { fontSize: 20, fontWeight: "800", marginTop: 12 },
  entrar: {
    fontSize: 60,
    fontWeight: "800",
    marginTop: 20,
    color: "#000",
    textAlign: "left",
  },
  txt: { color: "#0004FF", fontSize: 16, marginTop: 90, flexDirection: "row" },
  txt1: { color: "#000", fontSize: 16, flexDirection: "row", marginTop: 90 },
  label: { fontSize: 14, fontWeight: "500", marginBottom: 6, marginTop: 15 },
  headerTitle1: { fontSize: 18, fontWeight: "600", marginLeft: 12 },
  endereco: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    textAlign: "center",
    fontSize: 12,
    color: "#fff",
    paddingTop: 8,
  },

  // ---------------- Inputs ----------------
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    backgroundColor: "#f9f9f9",
    flex: 1,
  },
  inputEmail: {
    borderWidth: 1,
    borderColor: "#fff",
    padding: 12,
    borderRadius: 8,
    marginTop: 50,
    width: 350,
    backgroundColor: "#fff",
  },
  inputSenha: {
    borderColor: "#fff",
    padding: 12,
    borderRadius: 8,
    marginTop: 22,
    width: 350,
    backgroundColor: "#fff",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: 15,
    backgroundColor: "#fff",
    marginLeft: 10,
    width: 360,
  },
  inputContainer1: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: 15,
    marginTop: 30,
    backgroundColor: "#fff",
    marginLeft: 10,
    width: 360,
  },
  searchInput: { flex: 1, height: 40, fontSize: 16, color: "#141313ff" },

  // ---------------- Botões ----------------
  primaryBtn: {
    backgroundColor: "#2563eb",
    padding: 14,
    borderRadius: 30,
    alignItems: "center",
    width: "100%",
    marginTop: 50,
  },
  btnText: { color: "#fff", fontWeight: "700" },
  button: {
    backgroundColor: "#3B82F6",
    paddingVertical: 15,
    borderRadius: 30,
    alignItems: "center",
    marginBottom: 20,
    marginTop: 40,
  },
  buttonText: { color: "#fff", fontSize: 16, fontWeight: "bold" },
  btnentrar: {
    backgroundColor: "#fff",
    padding: 18,
    alignItems: "center",
    width: 350,
    marginTop: 12,
    borderWidth: 2,
    borderColor: "#D6CFCF",
    borderRadius: 12,
    flexDirection: "row",
    justifyContent: "center",
  },
  btnentrar1: {
    backgroundColor: "#fff",
    padding: 14,
    alignItems: "center",
    width: 350,
    marginTop: 100,
    borderWidth: 2,
    borderColor: "#D6CFCF",
    borderRadius: 12,
    flexDirection: "row",
    justifyContent: "center",
  },
  btnText1: {
    color: "#000",
    fontWeight: "700",
    fontSize: 20,
    paddingLeft: 10,
    flexDirection: "row",
  },
  cancelBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    paddingVertical: 12,
    marginRight: 8,
    alignItems: "center",
  },
  publishBtn: {
    flex: 1,
    backgroundColor: "#007bff",
    borderRadius: 8,
    paddingVertical: 12,
    marginLeft: 8,
    alignItems: "center",
  },
  cancelText: { color: "#333", fontWeight: "500" },
  publishText: { color: "#fff", fontWeight: "600" },
  footerButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 25,
  },

  // ---------------- Cards / Avatares ----------------
  card: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  avatarPlaceholder: {
    width: 52,
    height: 52,
    borderRadius: 10,
    backgroundColor: "#e6e6e6",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarLarge: {
    width: 86,
    height: 86,
    borderRadius: 44,
    backgroundColor: "#2563eb",
    alignItems: "center",
    justifyContent: "center",
  },
  // ---------------- Layout Home ----------------
  header: {
    width: "100%",
    paddingHorizontal: 16,
    paddingTop: 16,
    backgroundColor: "#007bff",
  },
  header1: { flexDirection: "row", alignItems: "center", marginBottom: 20 },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#b9b9b9ff",
    borderRadius: 45,
    paddingHorizontal: 12,
    margin: 16,
    marginTop: 12,
    marginBottom: 0,
  },
  SearchBar: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    alignItems: "center",
    marginTop: 16,
  },
  searchIcon: { marginRight: 8 },
  nearbyButton: {
    backgroundColor: "#007bff",
    padding: 12,
    borderRadius: 8,
    flex: 1,
    alignItems: "center",
    marginRight: 16,
  },

  // ---------------- Upload / Opções ----------------
  photoUpload: {
    height: 60,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ddd",
    marginTop: 10,
    marginBottom: 20,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f3f3f3",
  },
  preview: { width: 60, height: 60, borderRadius: 8 },
  option: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#007bff",
    borderRadius: 8,
    padding: 10,
    marginRight: 8,
    alignItems: "center",
  },
  optionSmall: {
    borderWidth: 1,
    borderColor: "#007bff",
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 14,
    marginRight: 8,
  },
  optionSelected: { backgroundColor: "#007bff", borderColor: "#007bff" },
  optionText: { color: "#007bff", fontWeight: "500" },

  // ---------------- Outros ----------------
  dividerContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
  },
  divider: { flex: 1, height: 1, backgroundColor: "#ccc" },
  orText: { marginHorizontal: 10, color: "gray", fontWeight: "bold" },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: "#007bff",
    borderRadius: 4,
  },
  socialRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 30,
  },
  Image: { width: 20, height: 20, resizeMode: "contain" },
  linha: { flexDirection: "row", alignItems: "center", marginVertical: 16 },
  linha1: { flex: 1, height: 1, backgroundColor: "#DADCE0" },
  filterContainer: { position: "absolute", right: 16, top: 120, zIndex: 10 },
  filterText: { color: "#fff", marginLeft: 6, fontWeight: "bold" },
  notificationItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderColor: "#f0f0f0",
  },
  header9: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 10,
    justifyContent: "space-between",
    marginHorizontal: 10,
  },
  headerTitle8: {
    fontSize: 18,
    fontWeight: "600",
    color: "#000",
  },
  addNew: {
    fontSize: 14,
    color: "#4A6CF7",
    fontWeight: "500",
  },
  option1: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 10,
    padding: 15,
    marginBottom: 12,
    backgroundColor: "#f9f9f9",
    marginHorizontal: 10,
  },
  optionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  optionText: {
    fontSize: 16,
    color: "#000",
  },
  button: {
    backgroundColor: "#4A6CF7",
    paddingVertical: 15,
    borderRadius: 10,
    alignItems: "center",
    marginBottom: 20,
    marginHorizontal: 10,
  },
  buttonTextT: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  modalBackground: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 25,
    width: "85%",
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 10,
  },
  modalDesc: {
    fontSize: 14,
    textAlign: "center",
    color: "#555",
    marginBottom: 20,
  },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 10,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    marginHorizontal: 5,
    borderRadius: 8,
    alignItems: "center",
  },
  cancelButton: {
    backgroundColor: "#E5E7EB",
  },
  returnButton: {
    backgroundColor: "#3B82F6",
  },
  cancelText: {
    color: "#111",
    fontSize: 16,
    fontWeight: "600",
  },
  returnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
});
